export * from './info_tag/info_tag.model.js'
export * from './game_tag/game_tag.model.js'
export * from "./achievement/achievement.model.js";
export * from "./age_rating/age_rating.model.js";
export * from "./awards/awards.model.js";
export * from "./developer/developer.model.js";
export * from "./publisher/publisher.model.js";
export * from "./fact/fact.model.js";
export * from "./game_series/game_series.model.js";
export * from "./rating/rating.model.js";
export * from "./requirements/requirements.model.js";
export * from "./system_requirements/system_requirements.model.js";